### ISSUE TITLE
404 upon login

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TWI-library#19]
When login in from 
https://transkribus.eu/readTest/login/ 
the re-direct ends up in a 404 on 
https://transkribus.eu/library

**Comment by EvaMLang** [comment]
The 404 still exists and should be reproducable by the following scenario:

1) Start by clicking on "login" hyperlink (left of "register") on top right brings up https://transkribus.eu/readTest/login/?next=/readTest/login/ 

2) Providing credentials leads to a new page (https://transkribus.eu/readTest/login/ ) which displays the visually same page BUT without the "login"/"register" hyperlinks (why does this page exist?). If I click on the avatar, it actually tells me I am logged in already.

3) Providing credentials (again) gives me the 404 and leads me to https://transkribus.eu/library

**Comment by cziaarm** [comment]
Sorry for closing this one.

I can see that if I follow login link from the login page so that the next=/readTest/login/.... that it made it's way to a 404

Then I fixed it :)

**Comment by EvaMLang** [comment]
The bug still exists. If I click on "Login" (left of "register"), I end up at https://transkribus.eu/readTest/login/?next=/readTest/login/  
Entering credentials I get to see the login screen AGAIN (https://transkribus.eu/readTest/login/ - now already logged in! Should be redirected to library instead), before I enter my credentials AGAIN and end up at https://transkribus.eu/readTest/library/ (where I want to be).

So, 404 gone but redirect linked to "Login" hyperlink/button needs to be abolished before I can finally close this issue.

Thanks

**Comment by cziaarm** [comment]
404 gone, superfluous login link raise separately as Transkribus/TWI-mc#56
